# Generated by Django 6.0.1 on 2026-01-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('hr', 'Personalwesen'), ('department_manager', 'Abteilungsleiter'), ('team_leader', 'Teamleiter'), ('group_leader', 'Gruppenleiter'), ('employee', 'Mitarbeiter')], default='employee', max_length=20, verbose_name='Rolle'),
        ),
    ]
