# Generated by Django 6.0.1 on 2026-01-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='subscription_plan',
            field=models.CharField(choices=[('low', 'Low Budget - Basis'), ('mid', 'Mid Budget - Standard'), ('high', 'High Budget - Premium')], default='low', max_length=10, verbose_name='Abonnement-Plan'),
        ),
    ]
