# Generated by Django 6.0.1 on 2026-02-08 14:28

import django.db.models.deletion
from django.db import migrations, models


def check_and_remove_field(apps, schema_editor):
    """Entferne subscription_plan nur wenn es existiert"""
    db_alias = schema_editor.connection.alias
    Organization = apps.get_model('accounts', 'Organization')
    
    # Prüfe ob Feld existiert
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("PRAGMA table_info(accounts_organization);")
        columns = [row[1] for row in cursor.fetchall()]
        
        if 'subscription_plan' in columns:
            # Feld existiert, entfernen
            schema_editor.remove_field(
                Organization,
                Organization._meta.get_field('subscription_plan')
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_theme_preference'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        # Entferne Feld nur wenn es existiert
        migrations.RunPython(check_and_remove_field, migrations.RunPython.noop),
        migrations.AddField(
            model_name='organization',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='subscriptions.subscription', verbose_name='Subscription'),
        ),
    ]
