# Generated by Django 5.2.4 on 2026-02-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_theme_preference'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='subscriptions.subscription', verbose_name='Subscription'),
        ),
    ]
