# Generated by Django 6.0.1 on 2026-02-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_organization_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial_completed',
            field=models.BooleanField(default=False, verbose_name='Tutorial abgeschlossen'),
        ),
    ]
