# Generated by Django 6.0.1 on 2026-02-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_organization_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_early_access',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, erhält diese Organization dauerhaft die vergünstigten Early-Access Preise', verbose_name='Early-Access Kunde'),
        ),
    ]
