# Generated by Django 6.0.1 on 2026-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_is_early_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_trial',
            field=models.BooleanField(default=True, help_text='Wenn aktiviert, wird der Starter-Plan als kostenlose Testversion angezeigt', verbose_name='Ist Trial'),
        ),
    ]
