# Generated by Django 6.0 on 2026-02-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_is_trial_to_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Demo-Organisationen werden täglich zurückgesetzt und dienen der Portfolio-Präsentation', verbose_name='Demo-Organisation'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Kunden-ID'),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Abonnement-ID'),
        ),
    ]
