# Generated by Django 6.0.1 on 2026-02-01 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default='starter', max_length=20)),
                ('max_departments', models.IntegerField(default=1)),
                ('max_employees', models.IntegerField(default=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=29.0, max_digits=10)),
                ('price_per_employee', models.DecimalField(decimal_places=2, default=1.5, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('subscription_start_date', models.DateField(auto_now_add=True)),
                ('subscription_end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
