# Generated by Django 6.0.1 on 2026-02-09 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyAccessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Early-Access Startdatum')),
                ('duration_months', models.IntegerField(default=6, verbose_name='Dauer in Monaten')),
                ('max_customers', models.IntegerField(default=30, verbose_name='Maximale Kundenanzahl')),
                ('is_active', models.BooleanField(default=True, verbose_name='Early-Access aktiv')),
            ],
            options={
                'verbose_name': 'Early-Access Einstellungen',
                'verbose_name_plural': 'Early-Access Einstellungen',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_early_access',
            field=models.BooleanField(default=False, help_text='Kunden mit Early-Access bekommen dauerhaft reduzierte Preise', verbose_name='Early-Access Kunde'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximaler monatlicher Preis (nur für Business Tier)', max_digits=10, null=True, verbose_name='Preisobergrenze'),
        ),
    ]
