# Generated by Django 6.0 on 2026-02-19 03:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_demo_and_stripe_fields'),
        ('subscriptions', '0002_earlyaccesssettings_subscription_is_early_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price_per_employee',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, verbose_name='Stripe Payment Intent ID')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, verbose_name='Stripe Checkout Session ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag')),
                ('currency', models.CharField(default='eur', max_length=3, verbose_name='Währung')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('succeeded', 'Erfolgreich'), ('failed', 'Fehlgeschlagen'), ('canceled', 'Storniert'), ('refunded', 'Erstattet')], default='pending', max_length=20, verbose_name='Status')),
                ('tier', models.CharField(blank=True, max_length=20, verbose_name='Abonniertes Tier')),
                ('billing_period_start', models.DateField(verbose_name='Abrechnungsbeginn')),
                ('billing_period_end', models.DateField(blank=True, null=True, verbose_name='Abrechnungsende')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='accounts.organization', verbose_name='Organisation')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='subscriptions.subscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Zahlungsaufzeichnung',
                'verbose_name_plural': 'Zahlungsaufzeichnungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
