# Generated by Django 6.0.1 on 2026-01-25 19:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('fulltime', 'Vollzeit'), ('parttime', 'Teilzeit'), ('minijob', 'Minijob'), ('werkstudent', 'Werkstudent'), ('apprentice', 'Auszubildende/r')], max_length=20, verbose_name='Beschäftigungsart')),
                ('min_hours_per_week', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. Wochenstunden')),
                ('max_hours_per_week', models.DecimalField(decimal_places=2, default=40, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Max. Wochenstunden')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stundenlohn (€)')),
                ('hire_date', models.DateField(verbose_name='Einstellungsdatum')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitarbeiter',
                'verbose_name_plural': 'Mitarbeiter',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], null=True, verbose_name='Wochentag')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='Spezifisches Datum')),
                ('start_time', models.TimeField(verbose_name='Von')),
                ('end_time', models.TimeField(verbose_name='Bis')),
                ('availability_type', models.CharField(choices=[('available', 'Verfügbar'), ('unavailable', 'Nicht verfügbar'), ('preferred', 'Bevorzugt')], default='available', max_length=20, verbose_name='Verfügbarkeitstyp')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='shifts.employee')),
            ],
            options={
                'verbose_name': 'Verfügbarkeit',
                'verbose_name_plural': 'Verfügbarkeiten',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('sick', 'Krank'), ('vacation', 'Urlaub'), ('other', 'Sonstiges')], max_length=20, verbose_name='Abwesenheitstyp')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('document', models.FileField(blank=True, null=True, upload_to='absence_documents/', verbose_name='Dokument (z.B. Krankmeldung)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='shifts.employee', verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Abwesenheit',
                'verbose_name_plural': 'Abwesenheiten',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qualifikation')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Qualifikation',
                'verbose_name_plural': 'Qualifikationen',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='qualifications',
            field=models.ManyToManyField(blank=True, related_name='employees', to='shifts.qualification', verbose_name='Qualifikationen'),
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('start_time', models.TimeField(verbose_name='Startzeit')),
                ('end_time', models.TimeField(verbose_name='Endzeit')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht'), ('completed', 'Abgeschlossen')], default='draft', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.employee', verbose_name='Mitarbeiter')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Schicht',
                'verbose_name_plural': 'Schichten',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_swaps', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('requesting_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_swaps', to='shifts.employee', verbose_name='Anfragender Mitarbeiter')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='shifts.shift', verbose_name='Schicht')),
                ('target_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swap_requests', to='shifts.employee', verbose_name='Ziel-Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Tauschwunsch',
                'verbose_name_plural': 'Tauschwünsche',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Vorlagenname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Schichtvorlage',
                'verbose_name_plural': 'Schichtvorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Schichttyp')),
                ('start_time', models.TimeField(verbose_name='Startzeit')),
                ('end_time', models.TimeField(verbose_name='Endzeit')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='Farbe (Hex)')),
                ('min_employees', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mindestbesetzung')),
                ('is_night_shift', models.BooleanField(default=False, verbose_name='Nachtschicht')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_types', to='accounts.organization')),
                ('required_qualifications', models.ManyToManyField(blank=True, related_name='shift_types', to='shifts.qualification', verbose_name='Erforderliche Qualifikationen')),
            ],
            options={
                'verbose_name': 'Schichttyp',
                'verbose_name_plural': 'Schichttypen',
                'ordering': ['start_time'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag'), (5, 'Samstag'), (6, 'Sonntag')], verbose_name='Wochentag')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shifts.employee', verbose_name='Mitarbeiter (optional)')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='shifts.shifttemplate')),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.shifttype', verbose_name='Schichttyp')),
            ],
            options={
                'verbose_name': 'Vorlagen-Eintrag',
                'verbose_name_plural': 'Vorlagen-Einträge',
                'ordering': ['weekday', 'shift_type__start_time'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shifts.shifttype', verbose_name='Schichttyp'),
        ),
        migrations.CreateModel(
            name='VacationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Von')),
                ('end_date', models.DateField(verbose_name='Bis')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vacations', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacation_requests', to='shifts.employee')),
            ],
            options={
                'verbose_name': 'Urlaubsantrag',
                'verbose_name_plural': 'Urlaubsanträge',
                'ordering': ['-created_at'],
            },
        ),
    ]
