# Generated by Django 6.0.1 on 2026-01-27 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='break_duration',
            field=models.IntegerField(default=0, help_text='Wird automatisch berechnet, kann aber überschrieben werden', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pausendauer (Minuten)'),
        ),
        migrations.AlterField(
            model_name='absencerecord',
            name='absence_type',
            field=models.CharField(choices=[('sick', 'Krank'), ('vacation', 'Urlaub'), ('vacation_wish', 'Urlaubswunsch'), ('kug', 'KUG'), ('other', 'Sonstiges')], max_length=20, verbose_name='Abwesenheitstyp'),
        ),
    ]
