# Generated by Django 6.0.1 on 2026-01-27 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shifttype_break_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifttype',
            name='is_night_shift',
        ),
        migrations.AddField(
            model_name='shifttype',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stunden zwischen 23:00-06:00 Uhr (wird automatisch berechnet)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nachtarbeitsstunden'),
        ),
    ]
