# Generated by Django 6.0.1 on 2026-01-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_remove_shifttype_is_night_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Abteilung'),
        ),
    ]
