# Generated by Django 6.0.1 on 2026-01-27 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stundenlohn (€)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='max_hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, default=40, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Max. Wochenstunden'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='min_hours_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min. Wochenstunden'),
        ),
    ]
