# Generated by Django 6.0.1 on 2026-01-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shifts', '0005_alter_employee_hourly_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Abteilungsname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shifts.department', verbose_name='Abteilung'),
        ),
    ]
