# Generated by Django 6.0.1 on 2026-01-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_department_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_types', to='shifts.department', verbose_name='Abteilung'),
        ),
    ]
