# Generated by Django 6.0.1 on 2026-01-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_shifttype_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications', to='shifts.department', verbose_name='Abteilung'),
        ),
    ]
