# Generated by Django 6.0.1 on 2026-01-31 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_subscription_plan'),
        ('shifts', '0008_qualification_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hourly_rate',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('fulltime', 'Vollzeit'), ('parttime', 'Teilzeit'), ('minijob', 'Minijob'), ('werkstudent', 'Werkstudent'), ('apprentice', 'Ausbildung')], max_length=20, verbose_name='Beschäftigungsart'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('shift_created', 'Neue Schicht'), ('shift_updated', 'Schicht geändert'), ('shift_deleted', 'Schicht gelöscht'), ('vacation_approved', 'Urlaub genehmigt'), ('vacation_rejected', 'Urlaub abgelehnt'), ('vacation_request', 'Neue Urlaubsanfrage')], max_length=50, verbose_name='Benachrichtigungstyp')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('is_emailed', models.BooleanField(default=False, verbose_name='E-Mail versendet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('related_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.shift', verbose_name='Zugehörige Schicht')),
                ('related_vacation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.vacationrequest', verbose_name='Zugehöriger Urlaubsantrag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Feiertagsname')),
                ('date', models.DateField(verbose_name='Datum')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Jährlich wiederkehrend')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Feiertag',
                'verbose_name_plural': 'Feiertage',
                'ordering': ['date'],
                'unique_together': {('organization', 'date', 'name')},
            },
        ),
    ]
