# Generated by Django 6.0.1 on 2026-01-31 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_subscription_plan'),
        ('shifts', '0009_remove_employee_hourly_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('training', 'Schulung'), ('project', 'Projekt-Termin'), ('company', 'Firmenevent'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Event-Typ')),
                ('start_datetime', models.DateTimeField(verbose_name='Start')),
                ('end_datetime', models.DateTimeField(verbose_name='Ende')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ort/Raum')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Ganztägig')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='shifts.employee', verbose_name='Teilnehmer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_datetime'],
            },
        ),
    ]
