# Generated by Django 6.0.1 on 2026-01-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0010_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shifts.event', verbose_name='Zugehöriges Event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('shift_created', 'Neue Schicht'), ('shift_updated', 'Schicht geändert'), ('shift_deleted', 'Schicht gelöscht'), ('vacation_approved', 'Urlaub genehmigt'), ('vacation_rejected', 'Urlaub abgelehnt'), ('vacation_request', 'Neue Urlaubsanfrage'), ('event_invitation', 'Event-Einladung'), ('event_updated', 'Event geändert'), ('event_deleted', 'Event abgesagt')], max_length=50, verbose_name='Benachrichtigungstyp'),
        ),
    ]
