# Generated by Django 6.0.1 on 2026-01-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0011_notification_related_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='editable_by_attendees',
            field=models.BooleanField(default=False, verbose_name='Von Teilnehmern bearbeitbar'),
        ),
    ]
