# Generated by Django 6.0.1 on 2026-02-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0012_event_editable_by_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='overtime_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Überstunden-Saldo'),
        ),
    ]
