# Generated by Django 6.0.1 on 2026-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0013_employee_overtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttype',
            name='works_on_saturday',
            field=models.BooleanField(default=False, help_text='Kann diese Schicht am Samstag geplant werden?', verbose_name='Samstags verfügbar'),
        ),
        migrations.AddField(
            model_name='shifttype',
            name='works_on_sunday',
            field=models.BooleanField(default=False, help_text='Kann diese Schicht am Sonntag geplant werden?', verbose_name='Sonntags verfügbar'),
        ),
    ]
