# Generated by Django 6.0.1 on 2026-02-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0014_shifttype_works_on_saturday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
